# Fly.io app configuration for Vapor API
# After `flyctl launch`, Fly will inject app name and other metadata.

app = "messenger-lovestory-api"
primary_region = "iad"

[build]
  # Uses Dockerfile in this directory

[env]
  LOG_LEVEL = "info"
  # DATABASE_URL and JWT_SECRET set via `flyctl secrets set`

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "connections"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "2s"
    path = "/health"

[deploy]
  strategy = "immediate"

