services:
  - type: web
    name: messenger-vapor
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/api/Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: messenger-vapor-db
          property: internalConnectionString
      - key: JWT_SECRET
        value: oVuzzt4wzNPtHqWePawHyhoXvpV1AKOKFSMDTqRgSkA=
      - key: AUTO_MIGRATE
        value: "true"

databases:
  - name: messenger-vapor-db
    plan: free
    region: oregon
